/*
    Seed.Actors.sql
    Actors who play main and key recurring characters. Birth/death dates are left NULL where not confirmed.
*/
PRINT N'Seeding Actor...';

MERGE dbo.Actor AS tgt
USING (VALUES
    -- The Original Series
    (N'William',     N'Shatner',         CAST('1931-03-22' AS DATE), CAST(NULL AS DATE)),
    (N'Leonard',     N'Nimoy',           '1931-03-26', '2015-02-27'),
    (N'DeForest',    N'Kelley',          '1920-01-20', '1999-06-11'),
    (N'James',       N'Doohan',          '1920-03-03', '2005-07-20'),
    (N'Nichelle',    N'Nichols',         '1932-12-28', '2022-07-30'),
    (N'George',      N'Takei',           '1937-04-20', NULL),
    (N'Walter',      N'Koenig',          '1936-09-14', NULL),
    (N'Majel',       N'Barrett',         '1932-02-23', '2008-12-18'),
    (N'Grace Lee',   N'Whitney',         '1930-04-01', '2015-05-01'),
    (N'Jeffrey',     N'Hunter',          '1926-11-25', '1969-05-27'),
    (N'Sean',        N'Kenney',          NULL,         NULL),
    (N'Booker',      N'Bradshaw',        NULL,         NULL),
    (N'Jane',        N'Wyatt',           '1910-08-12', '2006-10-20'),
    (N'Mark',        N'Lenard',          '1924-10-15', '1996-11-22'),
    (N'Celia',       N'Lovsky',          NULL,         NULL),
    (N'Arlene',      N'Martel',          NULL,         NULL),
    (N'Ricardo',     N'Montalbán',       '1920-11-25', '2009-01-14'),
    (N'Roger C.',    N'Carmel',          '1932-09-27', '1986-11-11'),
    (N'John',        N'Colicos',         '1928-12-10', '2000-03-06'),
    (N'Michael',     N'Ansara',          '1922-04-15', '2013-07-31'),
    (N'William',     N'Campbell',        '1923-10-30', '2011-04-28'),
    (N'John',        N'Winston',         NULL,         NULL),
    (N'Bruce',       N'Hyde',            NULL,         NULL),
    (N'Eddie',       N'Paskey',          NULL,         NULL),
    (N'Glenn',       N'Corbett',         NULL,         NULL),
    (N'Gary',        N'Lockwood',        NULL,         NULL),
    (N'Joan',        N'Collins',         '1933-05-23', NULL),
    (N'Stanley',     N'Adams',           NULL,         NULL),
    -- The Next Generation
    (N'Patrick',     N'Stewart',         '1940-07-13', NULL),
    (N'Jonathan',    N'Frakes',          '1952-08-19', NULL),
    (N'LeVar',       N'Burton',          '1957-02-16', NULL),
    (N'Michael',     N'Dorn',            '1952-12-09', NULL),
    (N'Gates',       N'McFadden',        '1949-03-02', NULL),
    (N'Marina',      N'Sirtis',          '1955-03-29', NULL),
    (N'Brent',       N'Spiner',          '1949-02-02', NULL),
    (N'Wil',         N'Wheaton',         '1972-07-29', NULL),
    (N'Denise',      N'Crosby',          '1957-11-24', NULL),
    (N'Diana',       N'Muldaur',         '1938-08-19', NULL),
    (N'Whoopi',      N'Goldberg',        '1955-11-13', NULL),
    (N'Colm',        N'Meaney',          '1953-05-30', NULL),
    (N'Rosalind',    N'Chao',            '1957-09-23', NULL),
    (N'John',        N'de Lancie',       '1948-03-20', NULL),
    (N'Dwight',      N'Schultz',         '1947-11-24', NULL),
    (N'Michelle',    N'Forbes',          '1965-01-08', NULL),
    (N'Robert',      N'O''Reilly',       NULL,         NULL),
    (N'Tony',        N'Todd',            '1954-12-04', '2024-11-06'),
    (N'Brian',       N'Bonsall',         '1981-12-03', NULL),
    (N'Patti',       N'Yasutake',        NULL,         NULL),
    (N'Gwynyth',     N'Walsh',           NULL,         NULL),
    (N'Barbara',     N'March',           NULL,         NULL),
    (N'Ashley',      N'Judd',            '1968-04-19', NULL),
    (N'Jonathan',    N'Del Arco',        NULL,         NULL),
    (N'Andreas',     N'Katsulas',        '1946-05-18', '2006-02-13'),
    (N'Suzie',       N'Plakson',         NULL,         NULL),
    (N'Elizabeth',   N'Dennehy',         NULL,         NULL),
    (N'Natalia',     N'Nogulich',        NULL,         NULL),
    (N'Jennifer',    N'Hetrick',         NULL,         NULL),
    (N'Susan',       N'Gibney',          NULL,         NULL),
    (N'Daniel',      N'Davis',           NULL,         NULL),
    (N'Carel',       N'Struycken',       NULL,         NULL),
    (N'Eric',        N'Menyuk',          NULL,         NULL),
    (N'Hallie',      N'Todd',            NULL,         NULL),
    -- Deep Space Nine
    (N'Avery',       N'Brooks',          '1948-10-02', NULL),
    (N'René',        N'Auberjonois',     '1940-06-01', '2019-12-08'),
    (N'Nana',        N'Visitor',         '1957-07-26', NULL),
    (N'Terry',       N'Farrell',         '1963-11-19', NULL),
    (N'Nicole',      N'de Boer',         '1970-12-20', NULL),
    (N'Alexander',   N'Siddig',          '1965-11-21', NULL),
    (N'Armin',       N'Shimerman',       '1949-11-05', NULL),
    (N'Cirroc',      N'Lofton',          '1978-08-05', NULL),
    (N'Max',         N'Grodénchik',      '1952-11-12', NULL),
    (N'Aron',        N'Eisenberg',       '1969-01-06', '2019-09-21'),
    (N'Andrew J.',   N'Robinson',        '1942-02-14', NULL),
    (N'Marc',        N'Alaimo',          '1942-05-07', NULL),
    (N'Hana',        N'Hatae',           NULL,         NULL),
    (N'Chase',       N'Masterson',       NULL,         NULL),
    (N'Louise',      N'Fletcher',        '1934-07-22', '2022-09-23'),
    (N'Philip',      N'Anglim',          NULL,         NULL),
    (N'Jeffrey',     N'Combs',           '1954-09-09', NULL),
    (N'Salome',      N'Jens',            NULL,         NULL),
    (N'Casey',       N'Biggs',           NULL,         NULL),
    (N'J. G.',       N'Hertzler',        NULL,         NULL),
    (N'Penny',       N'Johnson Jerald',  NULL,         NULL),
    (N'Brock',       N'Peters',          '1927-07-02', '2005-08-23'),
    (N'Wallace',     N'Shawn',           '1943-11-12', NULL),
    (N'Andrea',      N'Martin',          '1947-01-15', NULL),
    (N'Cecily',      N'Adams',           NULL,         NULL),
    (N'Mark Allen',  N'Shepherd',        NULL,         NULL),
    (N'James',       N'Darren',          '1936-06-08', '2024-09-02'),
    (N'Barry',       N'Jenner',          NULL,         NULL),
    (N'Kenneth',     N'Marshall',        NULL,         NULL),
    (N'Duncan',      N'Regehr',          NULL,         NULL),
    (N'Paul',        N'Dooley',          NULL,         NULL),
    (N'Felecia M.',  N'Bell',            NULL,         NULL),
    (N'Marc',        N'Worden',          NULL,         NULL),
    (N'Cyia',        N'Batten',          NULL,         NULL),
    (N'Tracy',       N'Middendorf',      NULL,         NULL),
    (N'Melanie',     N'Smith',           NULL,         NULL),
    (N'Camille',     N'Saviola',         NULL,         NULL),
    (N'William',     N'Sadler',          '1950-04-13', NULL),
    (N'James',       N'Sloyan',          NULL,         NULL),
    -- Voyager
    (N'Kate',        N'Mulgrew',         '1955-04-29', NULL),
    (N'Robert',      N'Beltran',         '1953-11-19', NULL),
    (N'Roxann',      N'Dawson',          '1958-09-11', NULL),
    (N'Robert Duncan', N'McNeill',       '1964-11-09', NULL),
    (N'Ethan',       N'Phillips',        '1955-02-08', NULL),
    (N'Robert',      N'Picardo',         '1953-10-27', NULL),
    (N'Tim',         N'Russ',            '1956-06-22', NULL),
    (N'Jennifer',    N'Lien',            '1974-08-24', NULL),
    (N'Garrett',     N'Wang',            '1968-12-15', NULL),
    (N'Jeri',        N'Ryan',            '1968-02-22', NULL),
    (N'Martha',      N'Hackett',         NULL,         NULL),
    (N'Alexander',   N'Enberg',          NULL,         NULL),
    (N'Tarik',       N'Ergin',           NULL,         NULL),
    (N'Susanna',     N'Thompson',        NULL,         NULL),
    (N'Alice',       N'Krige',           '1954-06-28', NULL),
    (N'Manu',        N'Intiraymi',       NULL,         NULL),
    (N'Scarlett',    N'Pomers',          NULL,         NULL),
    (N'Nancy',       N'Hower',           NULL,         NULL),
    (N'Richard',     N'Herd',            NULL,         NULL),
    (N'Brad',        N'Dourif',          '1950-03-18', NULL),
    (N'Raphael',     N'Sbarge',          NULL,         NULL),
    (N'Josh',        N'Clark',           NULL,         NULL),
    (N'John',        N'Savage',          NULL,         NULL),
    (N'Keegan',      N'de Lancie',       NULL,         NULL),
    -- Enterprise
    (N'Scott',       N'Bakula',          '1954-10-09', NULL),
    (N'Jolene',      N'Blalock',         '1975-03-05', NULL),
    (N'Connor',      N'Trinneer',        '1969-03-19', NULL),
    (N'Dominic',     N'Keating',         '1962-07-01', NULL),
    (N'Anthony',     N'Montgomery',      '1971-06-02', NULL),
    (N'Linda',       N'Park',            '1978-02-09', NULL),
    (N'John',        N'Billingsley',     '1960-05-20', NULL),
    (N'Vaughn',      N'Armstrong',       NULL,         NULL),
    (N'Gary',        N'Graham',          NULL,         NULL),
    (N'Matt',        N'Winston',         NULL,         NULL),
    (N'John',        N'Fleck',           NULL,         NULL),
    (N'Peter',       N'Weller',          '1947-06-24', NULL),
    (N'Scott',       N'MacDonald',       NULL,         NULL),
    (N'James',       N'Cromwell',        '1940-01-27', NULL),
    (N'Steven',      N'Culp',            NULL,         NULL),
    (N'Randy',       N'Oglesby',         NULL,         NULL),
    (N'Ada',         N'Maris',           NULL,         NULL),
    -- Strange New Worlds
    (N'Anson',       N'Mount',           '1973-02-25', NULL),
    (N'Ethan',       N'Peck',            '1986-03-02', NULL),
    (N'Rebecca',     N'Romijn',          '1972-11-06', NULL),
    (N'Jess',        N'Bush',            NULL,         NULL),
    (N'Christina',   N'Chong',           NULL,         NULL),
    (N'Celia Rose',  N'Gooding',         NULL,         NULL),
    (N'Melissa',     N'Navia',           NULL,         NULL),
    (N'Babs',        N'Olusanmokun',     NULL,         NULL),
    (N'Bruce',       N'Horak',           NULL,         NULL),
    (N'Martin',      N'Quinn',           NULL,         NULL),
    (N'Paul',        N'Wesley',          '1982-07-23', NULL),
    (N'Dan',         N'Jeannotte',       NULL,         NULL),
    (N'Carol',       N'Kane',            '1952-06-18', NULL),
    (N'Melanie',     N'Scrofano',        NULL,         NULL),
    (N'Gia',         N'Sandhu',          NULL,         NULL),
    (N'Mia',         N'Kirshner',        '1975-01-25', NULL),
    (N'Rong',        N'Fu',              NULL,         NULL),
    (N'Adrian',      N'Holmes',          NULL,         NULL)
) AS src (FirstName, LastName, BirthDate, DeathDate)
    ON tgt.FirstName = src.FirstName AND tgt.LastName = src.LastName
WHEN MATCHED AND EXISTS (SELECT tgt.BirthDate, tgt.DeathDate EXCEPT SELECT src.BirthDate, src.DeathDate)
    THEN UPDATE SET BirthDate = src.BirthDate, DeathDate = src.DeathDate
WHEN NOT MATCHED BY TARGET
    THEN INSERT (FirstName, LastName, BirthDate, DeathDate) VALUES (src.FirstName, src.LastName, src.BirthDate, src.DeathDate);
